import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavBar from "../ui/navbar";
import { HomeIcon, UsersIcon, UserPlusIcon, GlobeAltIcon, BellIcon, Cog6ToothIcon, QuestionMarkCircleIcon, PowerIcon } from "@heroicons/react/24/solid";
import SideBar, { EllipsisMenuItem, SideBarItem } from "../ui/sidebar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  
  return (
    <html lang="en">
      <body className={inter.className + ' flex'}>
        <SideBar profileMenu={
          <EllipsisMenuItem icon={<PowerIcon className="size-6 inline mr-2"></PowerIcon>}>
          </EllipsisMenuItem>
        }>
          <Link href={"home"}>
            <SideBarItem
                icon={<HomeIcon className="size-6"/>}
                text="Home"
                alert/>
          </Link>
          <Link href={"friend-list"}>
            <SideBarItem
                icon={<UsersIcon className="size-6"/>}
                text="Friend List"
                active/>
          </Link>
          <Link href={"add-friend"}>
            <SideBarItem
                icon={<UserPlusIcon className="size-6"/>}
                text="Add Friend"/>
          </Link>
          <SideBarItem
              icon={<GlobeAltIcon className="size-6"/>}
              text="Time Zone Map"
              alert/>
          <SideBarItem
              icon={<BellIcon className="size-6"/>}
              text="Notifications"/>
          <hr className="my-3"/>
          <SideBarItem
              icon={<Cog6ToothIcon className="size-6"/>}
              text="Settings"/>
          <SideBarItem
              icon={<QuestionMarkCircleIcon className="size-6"/>}
              text="Help"/>
        </SideBar>
        {children}
      </body>
    </html>
  );
}
